FROM openjdk:8-alpine
ADD target/GestionConjuntos-0.0.1-SNAPSHOT.jar /usr/share/GestionConjuntos-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["/usr/bin/java", "-jar", "/usr/share/GestionConjunto-0.0.1-SNAPSHOT.jar"]
